name: SwitchPvP
version: '1.0'
main: me.Pirat1345.switchPvP.SwitchPvP
api-version: '1.21'
commands:
  switchpvp:
    description: Main command for SwitchPvP minigame
    usage: |
      /switchpvp join - Join the game
      /switchpvp leave - Leave the game
      /switchpvp set lobby - Set lobby location
      /switchpvp set arena - Add arena spawn
      /switchpvp remove arena - Remove nearest arena spawn
      /switchpvp clear arenas - Clear all arena spawns
      /switchpvp list arenas - List all arena spawns
      /switchpvp set coreboard - Set leaderboard location
      /switchpvp remove coreboard - Remove leaderboard within 5 blocks
      /switchpvp reset stats - Reset all player statistics
      /switchpvp set countdown <seconds> - Change lobby countdown time
      /switchpvp kit create <name> - Create new kit
      /switchpvp kit delete <name> - Delete kit
      /switchpvp kit list - List all kits
    aliases: [spvp, switchpvp]